language: cpp
compiler:
  - gcc
os: linux
dist: focal
jobs:
  include:
    - name: python 3.6
      after_success:
        - coveralls --gcov-options '\-lp' -i $PWD/vm/ubpf_vm.c -i $PWD/vm/ubpf_jit_x86_64.c -i $PWD/vm/ubpf_loader.c
# command to install dependencies
install:
  - python3 -m pip install -r requirements.txt
  - python3 -m pip install cpp-coveralls
# command to run tests
script: 
  - make -C vm COVERAGE=1
  - nosetests -v
