#
# Copyright (c) 2022-present, IO Visor Project
# All rights reserved.
#
# This source code is licensed in accordance with the terms specified in
# the LICENSE file found in the root directory of this source tree.
#

name: Posix

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

      build_type:
        required: true
        type: string

      enable_sanitizers:
        required: true
        type: boolean

      enable_coverage:
        required: true
        type: boolean

      scan_build:
        required: true
        type: boolean

      upload_packages:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ${{ inputs.platform }}

    steps:
    - uses: actions/checkout@v3

    - name: Generate the cache key
      id: cache_key
      run: echo ::set-output name=VALUE::platform-${{ inputs.platform }}_type-${{ inputs.build_type }}_sanitizers-${{ inputs.enable_sanitizers }}_coverage-${{ inputs.enable_coverage }}_scan_build-${{ inputs.scan_build }}

    - name: Update the cache (ccache)
      uses: actions/cache@v1.0.3
      with:
        path: ccache
        key: ${{ steps.cache_key.outputs.VALUE }}_ccache

    - name: Create the build folders
      run: |
        mkdir -p \
          ccache

    - name: Install system dependencies (Linux)
      if: inputs.platform == 'ubuntu-20.04'
      run: |
        sudo apt-get install -y \
          ccache \
          ninja-build \
          cmake

        if [[ "${{ inputs.scan_build }}" == "true" ]] ; then
          sudo apt-get install -y \
            clang-tools
        fi

    - name: Install system dependencies (macOS)
      if: inputs.platform == 'macos-11'
      run: |
        brew install \
          cmake \
          ninja \
          ccache

    - name: Configure the project
      run: |
        export CCACHE_DIR="$(pwd)/ccache"

        if [[ "${{ inputs.scan_build }}" == "true" ]] ; then
          mkdir scan_build_report
          command_prefix="scan-build -o scan_build_report"
        fi

        ${command_prefix} cmake \
          -G Ninja \
          -S . \
          -B build \
          -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} \
          -DUBPF_ENABLE_COVERAGE=${{ inputs.enable_sanitizers }} \
          -DUBPF_ENABLE_SANITIZERS=${{ inputs.enable_coverage }} \
          -DUBPF_ENABLE_TESTS=true \
          -DUBPF_ENABLE_INSTALL=true

    - name: Build the project
      run: |
        export CCACHE_DIR="$(pwd)/ccache"

        if [[ "${{ inputs.scan_build }}" == "true" ]] ; then
          command_prefix="scan-build -o scan_build_report"
        fi

        ${command_prefix} cmake \
          --build build \
          -- -v

    - name: Upload scan-build report
      if: inputs.scan_build == true
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
      with:
        name: scan-build_report
        path: ${{github.workspace}}/scan_build_report
        retention-days: 5

    - name: Run the tests
      run: |
        cmake \
          --build build \
          --target test \
          -- -v

    - name: Run the install target
      run: |
        mkdir install
        export DESTDIR=$(pwd)/install

        cmake \
          --build build \
          --target install

    - name: Generate the DEB package
      if: inputs.platform == 'ubuntu-20.04'
      run: |
        cmake \
          -S . \
          -B build \
          -DUBPF_ENABLE_PACKAGE=true \
          -DCPACK_GENERATOR=DEB

        cmake \
          --build build \
          --target package

    - name: Generate the RPM package
      if: inputs.platform == 'ubuntu-20.04'
      run: |
        cmake \
          -S . \
          -B build \
          -DUBPF_ENABLE_PACKAGE=true \
          -DCPACK_GENERATOR=RPM

        cmake \
          --build build \
          --target package

    - name: Generate the TGZ package
      run: |
        cmake \
          -S . \
          -B build \
          -DUBPF_ENABLE_PACKAGE=true \
          -DCPACK_GENERATOR=TGZ

        cmake \
          --build build \
          --target package

    - name: Locate the packages
      id: package_locations
      if: inputs.upload_packages == true
      run: |
        echo ::set-output name=REL_DEB_PACKAGE_PATH::$(ls build/*.deb)
        echo ::set-output name=REL_RPM_PACKAGE_PATH::$(ls build/*.rpm)
        echo ::set-output name=REL_TGZ_PACKAGE_PATH::$(ls build/*.tar.gz)

    - name: Upload the DEB package
      if: inputs.upload_packages == true && inputs.platform == 'ubuntu-20.04'
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
      with:
        name: linux_deb_package
        path: ${{ steps.package_locations.outputs.REL_DEB_PACKAGE_PATH }}
        retention-days: 5

    - name: Upload the RPM package
      if: inputs.upload_packages == true && inputs.platform == 'ubuntu-20.04'
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
      with:
        name: linux_rpm_package
        path: ${{ steps.package_locations.outputs.REL_RPM_PACKAGE_PATH }}
        retention-days: 5

    - name: Upload the Linux TGZ package
      if: inputs.upload_packages == true && inputs.platform == 'ubuntu-20.04'
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
      with:
        name: linux_tgz_package
        path: ${{ steps.package_locations.outputs.REL_TGZ_PACKAGE_PATH }}
        retention-days: 5

    - name: Upload the macOS TGZ package
      if: inputs.upload_packages == true && inputs.platform == 'macos-11'
      uses: actions/upload-artifact@6673cd052c4cd6fcf4b4e6e60ea986c889389535
      with:
        name: macos_tgz_package
        path: ${{ steps.package_locations.outputs.REL_TGZ_PACKAGE_PATH }}
        retention-days: 5
